packages/cfd/src/Components/cfd-mt5-demo-account-display.tsx
packages/cfd/src/sass/cfd-dashboard.scss

Aizad / Fix CFD height css issue

---

packages/core/src/App/Containers/AcuityDownloadModal/acuity-download-modal.tsx

fix: updated download link in modal

---

packages/appstore/src/modules/trading-hub/index.tsx
packages/core/src/sass/account-wizard.scss

81217#amina/ in responsive, not able to scroll down if user adding all cfd accounts

---

packages/appstore/src/constants/routes-config.ts

fix: route config

---

packages/core/src/App/Components/Layout/Header/platform-dropdown.jsx
packages/core/src/App/Components/Layout/Header/platform-switcher.jsx
packages/core/src/App/Containers/Layout/header/default-header.jsx
packages/core/src/App/Containers/Layout/header/dtrader-header.jsx

Amina/fix: platform switcher in traders hub

---

packages/appstore/src/components/cfds-listing/cfds-listing.scss

chore: add modal styles

---

packages/appstore/src/components/containers/trading-app-card.tsx
packages/appstore/src/components/options-multipliers-listing/index.tsx
packages/cfd/src/Containers/compare-accounts-modal.tsx
packages/cfd/src/Containers/mt5-compare-table-content.tsx
packages/cfd/src/Containers/props.types.ts
packages/components/src/components/icon/icons.js
packages/components/stories/icon/icons.js
packages/core/src/Stores/traders-hub-store.js
packages/shared/src/utils/constants/account_flags.ts
packages/shared/src/utils/constants/content_flags.ts
packages/shared/src/utils/constants/index.ts

fix: content flag

---

packages/cfd/src/Components/props.types.ts
packages/cfd/src/Containers/compare-accounts-modal.tsx
packages/cfd/src/Containers/jurisdiction-modal/jurisdiction-modal.tsx
packages/cfd/src/Containers/mt5-compare-table-content.tsx
packages/cfd/src/Containers/props.types.ts
packages/core/src/Stores/traders-hub-store.js

Amina/ fix: filter jurisdictions

---

packages/appstore/src/components/account-transfer-modal/account-transfer-modal.tsx
packages/appstore/src/components/cfds-listing/index.tsx
packages/appstore/src/components/containers/trading-app-card-actions.tsx
packages/appstore/src/components/modals/modal-manager.tsx
packages/appstore/src/components/transfer-trade-button-group/transfer-trade-button-group.tsx
packages/core/src/Stores/traders-hub-store.js

chore: integrate transfer fund popup

---

packages/core/src/sass/app/_common/layout/app-layouts.scss

chore: show potrait blocker on tablet view

---

packages/appstore/src/modules/traders-hub/index.tsx
packages/core/src/App/Containers/Layout/header/dtrader-header.jsx

Hamza/fix: Dtrader page should not be shown for logged out user

---

packages/cfd/src/Stores/Modules/CFD/cfd-store.js

-  Fix demo cfd account creation

fix: demo cfd account creation

---

packages/appstore/src/components/cfds-listing/index.tsx
packages/appstore/src/components/containers/trading-app-card-actions.tsx
packages/appstore/src/components/containers/trading-app-card.scss
packages/appstore/src/components/containers/trading-app-card.tsx
packages/appstore/src/components/currency-switcher-card/real/real-account-switcher.tsx
packages/appstore/src/components/trade-button/trade-button.tsx
packages/appstore/src/components/transfer-trade-button-group/transfer-trade-button-group.tsx
packages/appstore/src/types/common.types.ts
packages/components/src/components/status-badge/status-badge.scss
packages/components/src/components/status-badge/status-badge.tsx
packages/core/src/App/Containers/CurrencySelectionModal/curreny-selection-modal.tsx

Amina/feat: account_status_for_cfd

---

packages/appstore/src/components/cfds-listing/index.tsx
packages/cashier/src/components/error-dialog/error-dialog.tsx
packages/cashier/src/pages/account-transfer/account-transfer-receipt/__tests__/account-transfer-receipt.spec.tsx
packages/cashier/src/pages/account-transfer/account-transfer-receipt/account-transfer-receipt.tsx
packages/cashier/src/pages/account-transfer/account-transfer.tsx
packages/cashier/src/stores/account-transfer-store.js
packages/core/src/Stores/traders-hub-store.js

bahar/85347 /Fix account transfer diel style issue

---

packages/core/src/App/Containers/CurrencySelectionModal/curreny-selection-modal.tsx

chore: hide unspported accounts

---

packages/appstore/src/components/CFDs/cfd-accounts.scss
packages/appstore/src/components/cfds-listing/cfds-listing.scss
packages/cfd/src/Containers/jurisdiction-modal/jurisdiction-modal-checkbox.tsx
packages/cfd/src/sass/cfd-dashboard.scss

Amina/fix: css styles

---

packages/core/src/Stores/traders-hub-store.js

Mahdiyeh/ fix: reloading of account_switcher

---

packages/appstore/src/components/currency-switcher-card/real/real-account-card.tsx
packages/appstore/src/components/currency-switcher-card/real/real-account-switcher.tsx
packages/components/src/components/status-badge/status-badge.tsx
packages/core/src/App/Containers/CurrencySelectionModal/curreny-selection-modal.tsx
packages/core/src/Stores/Helpers/client.js
packages/core/src/Stores/traders-hub-store.js

Amina/fix: multipliers_status_badge

---

packages/core/src/App/Containers/AccountSwitcher/account-switcher.jsx
packages/core/src/App/Containers/RealAccountSignup/add-or-manage-accounts.jsx
packages/core/src/App/Containers/RealAccountSignup/real-account-signup.jsx

fix: add or remove modal

---

packages/cfd/src/Components/__tests__/cfd-account-card.spec.tsx
packages/cfd/src/Components/__tests__/cfd-real-account-display.spec.js
packages/cfd/src/Components/cfd-account-card.tsx
packages/cfd/src/Components/cfd-mt5-demo-account-display.tsx
packages/cfd/src/Components/cfd-real-account-display.tsx
packages/cfd/src/Components/props.types.ts
packages/cfd/src/Constants/cfd-shared-strings.js
packages/cfd/src/Containers/__tests__/cfd-password-modal.spec.js
packages/cfd/src/Containers/cfd-dashboard.tsx
packages/cfd/src/Containers/cfd-password-modal.tsx
packages/cfd/src/Stores/Modules/CFD/cfd-store.js

Amina/ fix: mt5 dashboard fix

---

packages/account/src/Components/personal-details/__tests__/personal-details.spec.js
packages/account/src/Components/personal-details/personal-details.jsx

Amina/fix: next button disabled in eu signup

---

packages/cfd/src/Containers/mt5-compare-table-content.tsx

Amina 86116 fix error in dxtrade

---

packages/core/src/App/Containers/Modals/exit-traders-hub-modal/exit-traders-hub-modal.jsx
packages/core/src/Stores/traders-hub-store.js

Amina/fix: switching on exit traders modal

---

packages/core/src/App/Components/Layout/Header/toggle-menu-drawer.jsx
packages/core/src/App/Containers/Layout/header/trading-hub-header.jsx
packages/core/src/Stores/traders-hub-store.js

Amina/fix: acc switcher

---

packages/cfd/src/Containers/mt5-compare-table-content.tsx
packages/cfd/src/Containers/props.types.ts
packages/core/src/Stores/traders-hub-store.js

Amina/fix: compare account modal

---

packages/appstore/src/components/containers/currency-switcher-container.tsx
packages/appstore/src/components/currency-switcher-card/real/real-account-card.tsx
packages/appstore/src/components/currency-switcher-card/real/real-account-switcher.tsx
packages/core/src/Stores/traders-hub-store.js

Amina/ fix: mf currency switcher

---

packages/cfd/src/Stores/Modules/CFD/cfd-store.js
packages/core/src/Stores/traders-hub-store.js

Amina/fix: get_more_btn

---

packages/appstore/src/constants/regulators-modal-content.ts
packages/cfd/src/Constants/cfd_compare_account_content.ts

Amina/fix: regulators renaming

---

packages/cfd/src/Containers/cfd-password-modal.tsx

Amina/fix: success modal message

---

packages/appstore/src/components/main-title-bar/asset-summary.tsx
packages/core/src/Stores/traders-hub-store.js

Amina/fix: total assets to be shown based on selected region

---

packages/cashier/src/stores/account-transfer-store.js

-   fix default from account to account currency

george / rm86761 / mt5 transfer from is default to mt5 account instead of account currency

---

packages/appstore/src/components/main-title-bar/account-type-dropdown.tsx
packages/appstore/src/modules/onboarding/onboarding.tsx
packages/appstore/src/modules/tour-guide/tour-guide.tsx
packages/core/src/Stores/client-store.js

Mahdiyeh/ Fix: switch account to real for demo_low_risk

---

packages/cfd/src/Containers/cfd-dashboard.tsx

Amina/fix: redirect_to_traders_hub_on_entering_mt5_url

---

packages/cashier/src/stores/__tests__/account-transfer-store.spec.js
packages/cashier/src/stores/account-transfer-store.js

-   fix default transfer From account to current trading account (USD, BTC, etc.)
-   fix default transfer To account to selected Derived, Financial, DerivX, CFD's account
-   fix transfer To account to current trading account (USD, BTC, etc.) when the user selected Derived, Financial, DerivX, CFD's From account
-   [ ] New …

george / rm86761 / fix default transfer From/To accounts for Derived, Financial, DerivX, CFD's

---

packages/appstore/src/components/add-options-account/add-options-account.tsx
packages/appstore/src/components/cfds-listing/index.tsx
packages/appstore/src/components/modals/modal-manager.tsx
packages/appstore/src/components/options-multipliers-listing/index.tsx
packages/cfd/src/Constants/cfd_compare_account_content.ts
packages/cfd/src/Containers/mt5-compare-table-content.tsx

Amina/ fix: freeze_mf_acc_on_cooling_period

---

packages/appstore/src/modules/onboarding/onboarding.tsx

Amina/fix: close button on on boarding

---

packages/appstore/src/components/modals/modal-manager.tsx

Amina/fix: dmt5 paswrd

---

packages/appstore/src/components/modals/modal-manager.tsx
packages/appstore/src/modules/trading-hub/index.tsx
packages/cfd/src/Containers/cfd-dashboard.tsx
packages/cfd/src/Containers/cfd-server-error-dialog.tsx

Amina/fix: server error component

---

packages/appstore/src/components/cfds-listing/index.tsx
packages/appstore/src/components/onboarding-new/static-dashboard.tsx
packages/core/src/Stores/Helpers/client.js
packages/core/src/Stores/client-store.js
packages/core/src/Stores/traders-hub-store.js

-   Refactor: code changes fro Swap free

Refactor: code changes fro Swap free

---

packages/appstore/src/components/cfds-listing/index.tsx
packages/appstore/src/components/onboarding-new/static-dashboard.tsx
packages/cfd/src/Containers/jurisdiction-modal/jurisdiction-card.tsx
packages/core/src/Stores/traders-hub-store.js

refactor: refactored changes v1.0

---

packages/shared/src/utils/cfd/cfd.ts

-   sub_account_type type inference

refactor: sub_account_type error

---

packages/appstore/src/components/modals/account-type-modal/account-type-modal.tsx

-   removed localize from the switch case

refactor: remove localize

---

packages/appstore/src/components/modals/account-type-modal/account-type-modal.tsx
packages/cfd/src/Containers/cfd-password-modal.tsx
packages/cfd/src/Containers/dmt5-trade-modal.tsx

-   fix: remove line error + code smells

fix: remove line error + code smells

---

packages/cfd/src/Containers/cfd-dashboard.tsx

-   Primitive type safety check
-   [] Bug fix

fix: type error for primitive type

---

packages/appstore/src/components/onboarding-new/static-dashboard.tsx

-   eslint error + merge conflict

fix: conflict and eslint error

---

packages/cfd/src/Components/cfd-dxtrade-demo-account-display.tsx
packages/cfd/src/Components/cfd-mt5-demo-account-display.tsx
packages/cfd/src/Components/cfd-real-account-display.tsx
packages/cfd/src/Containers/cfd-dashboard.tsx
packages/cfd/src/Containers/dmt5-trade-modal.tsx

-   Changed back the type to original 

Update swapfree code refactoring

---

packages/cfd/types.ts

fix: circle ci store import error

---

packages/appstore/src/components/onboarding-new/static-dashboard.scss

-   Screen Getting Expanded on 5 and 6 Onboarding step

fix: get more button screen getting expanded

---

packages/cfd/types.ts
packages/hooks/src/useHasSwapFreeAccount.ts

-   suggestions refactored
- Documentation Comments
- Remove unused type
- rename the variable
- …

refactor: suggestions resolved

---

packages/hooks/src/index.ts

-   Removed SwitchToRealAccount hook

fix: Merge conflict resolve

---

packages/appstore/src/components/cfds-listing/index.tsx
packages/appstore/src/components/containers/trading-app-card.tsx

-   Translation + Demo label removed
-   [x] Translation to code

fix: translation and demo label removed

---

packages/appstore/src/components/containers/trading-app-card.tsx

-   Merge conflicts in Trading-app-card

fix: merge conflicts demo text in tradig-app-card

---

packages/cfd/src/Constants/jurisdiction-contents.ts

fix: synthetics added and forex addition and deletion

---

packages/cfd/src/Containers/dynamic-leverage/dynamic-leverage-market-card.tsx

Please provide a summary of the change.
Please provide some screenshots of the change.

feat: :bug: passed string to localize instead of a variable

---

packages/cfd/src/Containers/dynamic-leverage/__test__/dynamic-leverage-market-card.spec.tsx
packages/cfd/src/Containers/dynamic-leverage/dynamic-leverage-market-card.tsx
packages/cfd/src/Containers/dynamic-leverage/dynamic-leverage-table-column-header.tsx
packages/cfd/src/Containers/props.types.ts

Please provide a summary of the change.
Please provide some screenshots of the change.

Arshad/CFDS-637/Dynamic Leverage

---

packages/appstore/src/components/cfds-listing/cfds-listing.scss
packages/cfd/src/Containers/jurisdiction-modal/__test__/jurisdiction-modal-title.spec.tsx
packages/cfd/src/Containers/jurisdiction-modal/__test__/jurisdiction-modal.spec.tsx

Please provide a summary of the change.
Please provide some screenshots of the change.

Arshad/Dynamic Leverage Changes

---

packages/appstore/src/components/cfds-listing/cfds-listing.scss

Please provide a summary of the change.
Please provide some screenshots of the change.

Arshad/CFDS-1019/ Jurisdiction card layout Fix
